spring:
  # 配置数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?autoReconnect=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: mysql2018
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置 JPA 相关信息
  jpa:
    hibernate:
      ddl-auto: update  # 更新或创建数据表，如果数据表不存在就创建，存在就更新
    show-sql: true  # 在控制台打印底层执行的 sql

